# Generated by Django 4.0.2 on 2022-03-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('restaurants', '0001_initial'),
        ('blogs', '0002_alter_blogpost_author'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_user_delete_userextended'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserExtended',
        ),
    ]
