# Generated by Django 4.0.2 on 2022-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow_like_remove_likes_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='username',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
