# Generated by Django 4.0.2 on 2022-03-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userextended_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
