# Generated by Django 4.0.2 on 2022-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_like_restaurant_remove_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
