# Generated by Django 4.0.2 on 2022-03-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
