# Generated by Django 4.0.2 on 2022-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userextended_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
