# Generated by Django 4.0.2 on 2022-03-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_notifications'),
        ('accounts', '0009_alter_userextended_email'),
    ]

    operations = [
    ]
