# Generated by Django 4.0.2 on 2022-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userextended_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextended',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userextended',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userextended',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='userextended',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
