# Generated by Django 4.0.2 on 2022-03-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userextended_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
