# Generated by Django 4.0.2 on 2022-03-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userextended_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='username',
            field=models.CharField(default='User', max_length=15, unique=True),
        ),
    ]
