# Generated by Django 4.0.2 on 2022-03-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userextended_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='username',
            field=models.CharField(default='User', max_length=120, unique=True),
        ),
    ]
